export const IPC = {
  ping: 'app:ping',
  fsList: 'fs:list',
  fsRead: 'fs:read',
  fsWrite: 'fs:write',
  fsCreate: 'fs:create',
  fsRename: 'fs:rename',
  fsDelete: 'fs:delete',
  dialogOpenFolder: 'dialog:open-folder',
  termCreate: 'term:create',
  termData: 'term:data',
  termResize: 'term:resize',
  termDispose: 'term:dispose',
  fccStatus: 'fcc:status',
  fccStart: 'fcc:start',
  fccStop: 'fcc:stop',
  fccDetect: 'fcc:detect',
  chatStart: 'chat:start',
  chatSend: 'chat:send',
  chatStop: 'chat:stop',
  setChatSettings: 'settings:set',
  setTitleBarOverlay: 'window:set-titlebar-overlay',
  // events main -> renderer
  evtChat: 'chat:event',
  evtFcc: 'fcc:status-changed',
  evtTerm: 'term:output',
  evtFileModified: 'file:modified'
} as const;
