export const IPC = {
  ping: 'app:ping',
  fsList: 'fs:list',
  fsRead: 'fs:read',
  fsWrite: 'fs:write',
  fsCreate: 'fs:create',
  fsRename: 'fs:rename',
  fsDelete: 'fs:delete',
  fsCopy: 'fs:copy',
  fsSearch: 'fs:search',
  fsSearchContent: 'fs:search-content',
  dialogOpenFolder: 'dialog:open-folder',
  /** re-register a previously-open folder on startup (no dialog) */
  openFolderAt: 'fs:open-root',
  termCreate: 'term:create',
  termData: 'term:data',
  termResize: 'term:resize',
  termDispose: 'term:dispose',
  termRecent: 'term:recent',
  gitDiff: 'git:diff',
  gitInfo: 'git:info',
  gitStatus: 'git:status',
  gitAction: 'git:action',
  gitCommit: 'git:commit',
  gitStagedDiff: 'git:staged-diff',
  gitBranch: 'git:branch',
  gitHistory: 'git:history',
  gitShow: 'git:show',
  fccStatus: 'fcc:status',
  fccStart: 'fcc:start',
  fccStop: 'fcc:stop',
  fccDetect: 'fcc:detect',
  chatStart: 'chat:start',
  chatSend: 'chat:send',
  chatStop: 'chat:stop',
  chatApprove: 'chat:approve',
  /** send a live control_request to the running CLI (set_permission_mode,
   *  apply_flag_settings, …) — realtime change without restarting the chat */
  chatControl: 'chat:control',
  chatModels: 'chat:models',
  claudeSettingsGet: 'claude-settings:get',
  claudeSettingsSet: 'claude-settings:set',
  agentsList: 'agents:list',
  agentsRead: 'agents:read',
  agentsSave: 'agents:save',
  agentsDelete: 'agents:delete',
  clipboardReadImage: 'clipboard:read-image',
  historyList: 'history:list',
  historyOpen: 'history:open',
  historyDelete: 'history:delete',
  mcpGet: 'mcp:get',
  mcpSet: 'mcp:set',
  pluginsList: 'plugins:list',
  pluginsSet: 'plugins:set',
  setChatSettings: 'settings:set',
  setTitleBarOverlay: 'window:set-titlebar-overlay',
  appInfo: 'app:info',
  openExternal: 'shell:open-external',
  readAsset: 'fs:read-asset',
  // events main -> renderer
  evtChat: 'chat:event',
  evtFcc: 'fcc:status-changed',
  evtTerm: 'term:output',
  evtFileModified: 'file:modified'
} as const;
