import { autoUpdater, type UpdateInfo } from 'electron-updater';
import { IPC } from '@shared/ipc';
import type { UpdateState } from '@shared/types';

// Auto-update via electron-updater. The feed URL comes from `app-update.yml`
// (generated by electron-builder from the `publish` config) — it's only present
// in packaged builds, so initUpdater is gated on app.isPackaged in index.ts.
// All state is pushed to the renderer over IPC.evtUpdate.

export type { UpdateState };

export function initUpdater(win: Electron.BrowserWindow): void {
  autoUpdater.autoDownload = false;
  autoUpdater.autoInstallOnAppQuit = true;

  const send = (state: UpdateState): void => {
    if (!win.isDestroyed()) win.webContents.send(IPC.evtUpdate, state);
  };

  autoUpdater.on('checking-for-update', () => send({ status: 'checking' }));
  autoUpdater.on('update-available', (info: UpdateInfo) =>
    send({ status: 'available', version: info.version, notes: info.releaseNotes ? String(info.releaseNotes) : undefined })
  );
  autoUpdater.on('update-not-available', () => send({ status: 'none' }));
  autoUpdater.on('download-progress', (p) => send({ status: 'downloading', percent: Math.round(p.percent) }));
  autoUpdater.on('update-downloaded', (info: UpdateInfo) => send({ status: 'downloaded', version: info.version }));
  autoUpdater.on('error', (err) => send({ status: 'error', message: err?.message ?? String(err) }));
}

/** Check for a newer version. Errors (no feed / not packaged) are swallowed —
 *  the renderer learns from the event stream, never a throw. */
export function checkForUpdates(): void {
  void autoUpdater.checkForUpdates().catch(() => undefined);
}

export function downloadUpdate(): void {
  void autoUpdater.downloadUpdate().catch(() => undefined);
}

export function installUpdate(): void {
  autoUpdater.quitAndInstall();
}